### ISSUE TITLE
matrix to analysis results workflow

### ISSUE THREAD

**Issue by koenvandenberge** [kdkorthauer/scDD#1]
Hi,

Since the main `scDD` function takes an ExpressionSet object as input, but gene expression data is often represented as a numeric matrix. Therefore, a pipeline starting from a count matrix would be useful. However, when I try to implement this, I run in errors when running the scDD function.

For example, this block of code does not seem to do the trick:

`counts=matrix(round(abs(rnorm(100,sd=10))),nrow=10)`
`condition=factor(c(rep(1,5), rep(2,5)))`
`groupLevels=levels(condition)`
`condition1Counts = counts[,condition==groupLevels[1]]`
`condition2Counts = counts[,condition==groupLevels[2]]`
`countList = list(condition1=condition1Counts, condition2=condition2Counts)`
`countsNorm <- preprocess(countList, ConditionNames=paste0("condition",1:2), zero.thresh=1, median_norm=TRUE)`
`eset=ExpressionSet(countsNorm)`
`pData(eset) = data.frame(condition=condition)`
`prior_param=list(alpha=0.01, mu0=0, s0=0.01, a0=0.01, b0=0.01)`
`nperms <- 1000`
`res <- scDD(eset, prior_param=prior_param, permutations=nperms, testZeroes=FALSE, adjust.perms=TRUE)`

**Comment by kdkorthauer** [comment]
Hi Koen,

Thank you for the suggestion; I agree that it would be useful to provide a pipeline for users starting with a count matrix.  The code chunk you provide seems to work and doesn't throw any errors for me.  Could you send me the errors you are seeing, as well as the output of `sessionInfo()`?

Best,
Keegan

**Comment by koenvandenberge** [comment]
Hi Keegan,

Thank you for your reply.

The code I provided was to reproduce an error I ran into when analysing a real dataset. I have added the ExpressionSet in a dropbox folder so you could reproduce it: https://www.dropbox.com/sh/mf4hsukoxy95fwq/AACzM4yv-Ap5NckSlRqfDq5ma?dl=0

It is the dataset from this paper: http://www.ncbi.nlm.nih.gov/pubmed/21543516

This the error I get:
Error in if (G[1] == 1) { : missing value where TRUE/FALSE needed

And my sessionInfo:
 sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.3 (El Capitan)

locale:
[1] C/UTF-8/C/C/C/C

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] scDD_1.0.0          ROCR_1.0-7          gplots_2.17.0       pscl_1.4.9  
 [5] lattice_0.20-33     MASS_7.3-45         GEOquery_2.36.0     Biobase_2.30.0  
 [9] BiocGenerics_0.16.1 edgeR_3.12.0        limma_3.26.3        vimcom_1.2-7  
[13] setwidth_1.0-4     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.3          nloptr_1.0.4         futile.logger_1.4.1  plyr_1.8.3  
 [5] outliers_0.14        bitops_1.0-6         futile.options_1.0.0 tools_3.2.3  
 [9] mclust_5.1           lme4_1.1-10          testthat_0.11.0      digest_0.6.9  
[13] nlme_3.1-122         memoise_0.2.1        gtable_0.1.2         blockmodeling_0.1.8 
[17] Matrix_1.2-3         spam_1.3-0           coda_0.18-1          gridExtra_2.0.0  
[21] maps_3.0.2           fields_8.3-6         gtools_3.5.0         caTools_1.17.1  
[25] grid_3.2.3           XML_3.98-1.3         BiocParallel_1.4.3   arm_1.8-6  
[29] minqa_1.2.4          gdata_2.17.0         EBSeq_1.10.0         ggplot2_2.0.0  
[33] lambda.r_1.1.7       splines_3.2.3        scales_0.3.0         abind_1.4-3  
[37] colorspace_1.2-6     KernSmooth_2.23-15   RCurl_1.95-4.7       munsell_0.4.2  
[41] crayon_1.3.1

**Comment by kdkorthauer** [comment]
Hi Koen,

Ah, I see.  I was able to reproduce your error and I came across two issues that need to be resolved:
1. In the current version of scDD, the condition labels (`phenoData` slot) in the ExpressionSet need to be specified as integer values (1 or 2) instead of characters - see the man page of `scDD` function:
   
   > The `PhenoData` slot should contain a vector of numeric values (either 1 or 2) that indicates which condition each sample belongs to (in the same order as the columns of `assayData`)
   
   This is a limitation in flexibility of the code and I will work on updating it to accommodate character factor labels.  In the meantime, you can relabel the conditions as you have done in the example code snippet you provided in your first comment.
2. In the example ExpressionSet you supplied, there are many rows (genes) that contain almost all zeroes.  Since scDD fits mixture models to the expressed (nonzero) observations to discover the number of components, supplying genes with only one or two nonzero observations will also cause an error in the current version of scDD.  
   
   I also plan to update the code to provide a warning message in this situation, but still run on the remaining genes.  In the meantime, I recommend filtering out genes that are mostly zero in one or both conditions.  This can be done by specifying a value of `zero.thresh` in the `preprocess` function.  For example, the following code will remove genes that have zero values in 90% or more of the samples in one or both conditions:
   
   `countsNorm <- preprocess(countList, ConditionNames=paste0("condition",1:2), zero.thresh=0.9,   median_norm=TRUE)`

Best,
Keegan

**Comment by koenvandenberge** [comment]
Dear Keegan,

This clears things up. Thank you for the swift replies.

All the best,
Koen
