### ISSUE TITLE
error: groups incompatible with classification

### ISSUE THREAD

**Issue by mRcSchwering** [kdkorthauer/scDD#10]
I get this error

```
Error: BiocParallel errors
  element index: 76, 77, 78, 79, 80, 81, ...
  first error: groups incompatible with classification
```

when starting

```
se <- scDD(
  se, 
  prior_param = list(alpha = 0.01, mu0 = 0, s0 = 0.01, 
                     a0 = 0.01, b0 = 0.01),
  param = param,
  permutations = 0,
  testZeroes = FALSE
)
```

where param is

```
class: SnowParam
  bpisup: FALSE; bpworkers: 36; bptasks: 0; bpjobname: BPJOB
  bplog: FALSE; bpthreshold: INFO; bpstopOnError: TRUE
  bptimeout: 2592000; bpprogressbar: FALSE
  bpRNGseed: 
  bplogdir: NA
  bpresultdir: NA
  cluster type: SOCK
```

and se was created with a numeric, positive expression matrix like this

```
se <- SummarizedExperiment(
  assays = list("NormCounts" = m),
  colData = data.frame(condition = groups)
)
```

groups is a character vector containing "Group1" and "Group2" values.

The weird thing is, when I run this with just a few rows (e.g. 10), everything works fine.
Just if I run the whole matrix, this error occurs.

Where should I look for my error? What does this error usually mean?

Best
Marc

**Comment by kdkorthauer** [comment]
Hi Marc,

Thanks for bringing this to my attention. From the error message, it looks like the problem occurs in the mode-finding step, starting with row 76 (so that's why it works when you only use the first 10 rows). Is there something different about rows 76-81 compared to rows 1-10? Are the non-zero values made up of very few unique values? 

Have you applied any transformations on the normalized counts in `se`? The `scDD` function applies a log-transformation, so counts on the raw scale (not log-scale) should be used as input.

Best,
Keegan

**Comment by mRcSchwering** [comment]
I did use counts which were normalized with scran.
These should be log2 normalized so I transformed them back `m <- 2^m`.
I tried it with differently normalized counts too, which also didnt work.

I then did not do `m <- 2^m` and it worked without errors.
I assured that there are no negative values (`m[m < 0] <- 0`). 
However, this is probably wrong because m should then be on a log2 scale.

**Comment by kdkorthauer** [comment]
Hi Marc,

Can you check the properties of genes 76-81 compared to genes 1-10 in terms of the number of zeroes and the number of unique non-zero values? Does the function still throw an error if you randomize the condition labels (provide a null split)? 

If it would be easier, feel free to send me a subset of the data that throws the error (keegan@jimmy.harvard.edu) and I'll see if I can pinpoint the cause.

Best,
Keegan

**Comment by mRcSchwering** [comment]
Ok, here is rows 71:91 of `m` and `groups`: 
[grps.txt](https://github.com/kdkorthauer/scDD/files/862166/grps.txt)
[matrix.txt](https://github.com/kdkorthauer/scDD/files/862167/matrix.txt)
You can read them with `dget`.

```
library(scDD)
library(SummarizedExperiment)
m <- dget("matrix.txt")
groups <- dget("grps.txt")
```
Should be a numeric with dim 21, 298 and a character length 298.

```
str(m)
str(groups)
```

Like this, `m` has log2 transformed expression values.
`scDD` runs through but produces warnings:

```
se <- SummarizedExperiment(
  assays = list("NormCounts" = m),
  colData = data.frame(condition = groups)
)
se <- scDD(
    se, 
    prior_param = list(alpha = 0.01, mu0 = 0, s0 = 0.01, 
                       a0 = 0.01, b0 = 0.01),
    permutations = 0,
    testZeroes = FALSE
)
```
Now if I transform back `m` it is on a linear scale again, but `scDD` throws an error:

```
se <- SummarizedExperiment(
  assays = list("NormCounts" = 2^m),
  colData = data.frame(condition = groups)
)
se <- scDD(
  se, 
  prior_param = list(alpha = 0.01, mu0 = 0, s0 = 0.01, 
                     a0 = 0.01, b0 = 0.01),
  permutations = 0,
  testZeroes = FALSE
)
```

**Comment by kdkorthauer** [comment]
Hi Marc,

Excellent; thanks for sharing those objects!

I think I found the cause. It has to do with the loss of the 'zeroes' upon transforming the log-scale output from scran back to the original scale. On the log2-scale, if a zero value represents a true zero (no reads), then transforming those values to the raw scale with `2^m` will change the zero values to 1. Then scDD interprets them as a 1, instead of a zero and tries to include them in the expressed component of the model. This causes problems when there are lots of zeroes, as in the case of gene 7 in your example object `m`. 

Note that the log transformed output from scran uses an offset that is determined by the SCESet, with a default of 1. For example:

``` log2NormalizedCounts = log2(NormalizedCounts+offset)```

Thus, I'd recommend inputing raw values obtained by the following transformation:

```
log2NormalizedCounts[log2NormalizedCounts <0] <- 0
NormalizedCounts = 2^log2NormalizedCounts - offset
```

Using `offset=1` unless you have changed this default setting.  Hope that helps! Let me know if that doesn't solve the problem for you.

Best,
Keegan
