### ISSUE TITLE
scDD seems to fail on large matrices

### ISSUE THREAD

**Issue by yanwu2014** [kdkorthauer/scDD#2]
Works fine on matrices less than ~70k elements. 

Stack trace:

11 stop("data must be one dimensional") 
10 mvnX(data = data, prior = prior) 
9 eval(expr, envir, enclos) 
8 eval(mc, parent.frame()) 
7 mvn(modelName = mdl, data = data, prior = prior) 
6 mclustBIC(data = structure(-1.04299176277176, .Dim = c(1L, 1L
), .Dimnames = list("CTTTGGTCTGTN", NULL)), G = 1:5, modelNames = c("V"), 
    warn = FALSE) 
5 eval(expr, envir, enclos) 
4 eval(mc, parent.frame()) 
3 Mclust(y, warn = FALSE, modelNames = c("V"), G = 1:5) 
2 mclustRestricted(y[cond0 == 1], restrict = TRUE) 
1 scDD(gene.expressionset, prior_param = prior_param, permutations = nperms, 
    testZeroes = T, adjust.perms = F)

**Comment by kdkorthauer** [comment]
Hi,

Thank you for the issue report.  I have been able to run on much, much larger matrices, so I'm not sure the size is the main issue here.  Will you check and make sure that your gene expression object doesn't contain any genes that were not detected in any of the samples (i.e. a gene with all zeroes)?  

Best,
Keegan

**Comment by yanwu2014** [comment]
Hi Keegan,

Thanks so much for the quick response! Yeah there are no rows or columns with all zeros, and the matrix doesn't have any missing values. I get the same error on both linux and Windows systems and it doesn't seem to be related to memory limitations. I'm running R 3.3.0 and Bioconductor 3.3. 

Thanks again!
Yan

**Comment by kdkorthauer** [comment]
Hi,

Thanks for checking for zeroes/missing values.  I can't seem to reproduce the error with large matrices.  

One more thing you can check: are there any genes in your dataset that only contain a single sample with a nonzero entry?  Similar to the all zeroes case, this would throw an error since scDD expects that there is a vector of nonzero values for each gene.  If there are any genes that are zero in every sample except one, please try removing such genes before running scDD.  Let me know if that works for you.

Best,
Keegan
