### ISSUE TITLE
Simulation error if n genes is zero

### ISSUE THREAD

**Issue by lazappi** [kdkorthauer/scDD#4]
Hi

I have been playing around with your simulation function and am getting an error if any of `nDE`, `nDP`, `nDM`, `nDB`, `nEE` or `nEP` is less than 2. 

If one of them is set to 0 you get the following error (and traceback):

``` r
Error in if (xor(((x[n] - mean(x)) < (mean(x) - x[1])), opposite)) { : argument is of length zero 

outliers::grubbs.test(log(a + 1)) 
calcMV(Dataset1[samplename[x], ], FC = 1, FC.thresh = FC2[x]^(-1/2), threshold = 3, include.zeroes = FALSE) 
FUN(X[[i]], ...) 
lapply(X = X, FUN = FUN, ...) 
sapply(1:length(samplename), function(x) calcMV(Dataset1[samplename[x], ], FC = 1, FC.thresh = FC2[x]^(-1/2), threshold = 3, include.zeroes = FALSE)) 
t(sapply(1:length(samplename), function(x) calcMV(Dataset1[samplename[x], ], FC = 1, FC.thresh = FC2[x]^(-1/2), threshold = 3, include.zeroes = FALSE))) 
singleCellSimu(Dataset1, Method = "DP", index, FC, modeFC, DP = c(0.5, 0.5), Validation = FALSE, numGenes = nEP, numDE = 0, numSamples = numSamples, generateZero = generateZero, constantZero = constantZero, varInflation) 
```

If any of them are 1 you get this error instead:

``` r
Error in apply(Dataset1[samplename, ], 1, function(a) length(which(a ==  :  dim(X) must have a positive length 
stop("dim(X) must have a positive length") 
apply(Dataset1[samplename, ], 1, function(a) length(which(a == 0))/length(a))
as.matrix(apply(Dataset1[samplename, ], 1, function(a) length(which(a == 0))/length(a)))
singleCellSimu(Dataset1, Method = "DP", index, FC, modeFC, DP = c(0.5, 0.5), Validation = FALSE, numGenes = nEP, numDE = 0, numSamples = numSamples, generateZero = generateZero, constantZero = constantZero, varInflation)
```

Running the simulation also seems to leave behind orphaned R sessions (at least when running RStudio on OSX). If run multiple times in a row they build up and the simulation starts to hang.

**Comment by kdkorthauer** [comment]
Hi lazappi,

Thanks for catching this error.  I have solved the issue and you should now be able to simulate gene sets where one or more of the different pattern numbers is set to either 0 or 1 (with the exception of setting them all to 0 - this will still throw an error, but now with an informative error message).  Please remove the current version from your library and then install the updated version on the master branch with 

``` r
remove.packages('scDD')
devtools::install_github('kdkorthauer/scDD')
```

and see that it now performs as expected.  

With regard to the second issue of orphaned R sessions, I suspect that this is due to the R session opening up parallel processes when executing the simulation function, and then halting upon encountering an error (as you were when setting one of the n genes values to zero or one), so that the parallel processes were not cleaned up and terminated properly.  If you notice this happening again even with the patched simulation code, please let me know by submitting a new issue.  Thanks again!

Best,
Keegan

**Comment by lazappi** [comment]
Great! Thanks for the quick response.
