### ISSUE TITLE
R 3.4 Issue

### ISSUE THREAD

**Issue by WillHackett22** [kdkorthauer/scDD#6]
Hello,
I was using the older version of scDD on one machine so I know it was working. I just tried to use it on a new machine (Windows [both machines are windows]). It keeps telling me that it can't install scDD because it doesn't have R 3.4, but I am updated to the most recent R version which is R 3.3.2. I think it might mean Bioconductor 3.4, but I'm not certain. I tried to do a local manual install and ignore the R call up, but then got an error while trying to use scDD about a lack of a valid SummarizedExperiment despite not changing how I run it at all from the other version.
Hoping you can help me out.
Thanks,
Will

**Comment by kdkorthauer** [comment]
Hi Will,

Thanks for your interest in using scDD.   I apologize for the inconveniences that may have been caused by the recent changes associated with the acceptance of scDD into the [Bioconductor Project](https://www.bioconductor.org).  As you have noticed, the most recent version of [scDD on Bioconductor](http://bioconductor.org/packages/devel/bioc/html/scDD) (mirrored on the [master branch](https://github.com/kdkorthauer/scDD)) requires that the development version of R 3.4 be installed on the system.  This is a requirement for packages to be included in Bioconductor initially.  When a package is initially accepted to Bioconductor, it is placed only in the Development version of Bioconductor (3.5), where it remains until the next stable release (twice a year).  When a package moves to the stable release, it will then depend on the current stable release version of R.  

I recognize that having the development version of R installed may be impractical, so in the meantime I have also created a version of scDD where this dependency has been removed, which you can find on the [develop branch](https://github.com/kdkorthauer/scDD/tree/develop) and install with:

```
install.packages("devtools")

devtools::install_github("kdkorthauer/scDD", ref="develop")
```

The second issue you have encountered is also related to the transition to Bioconductor.  When the package was undergoing code review as part of the submission process, it became clear that using the ```SummarizedExperiment``` class for the main data objects would be more efficient than using the ```ExpressionSet``` class.  One tangible benefit is that with the ```SummarizedExperiment``` class implemented, the results can now be stored in the same object as the data, and accessed with handy accessor functions (see for example the new ```results``` function and its example usage).  The new objects are actually very similar to construct to the earlier ```ExpressionSet``` objects, and instruction is provided in Section 6.1 of the vignette entitled "Constructing a SummarizedExperiment object".  If you have any further questions about this, I'd be happy to help you in modifying your code.

However, I also recognize that this change can be inconvenient if you already have code that depends on the previous version.  If you'd rather, you can install an earlier version directly through GitHub (since changes are tracked via commits, and major changes through [releases](https://github.com/kdkorthauer/scDD/releases)).  For example, if you'd like to install release 3 - version 0.99.0 (the version just prior to undergoing code review for Bioconductor), you can use:

```
install.packages("devtools")

devtools::install_github("kdkorthauer/scDD", ref="0.99.0")
```

You could also reference a specific commit using the ```ref``` field if there is a more specific version you desire.  

I hope this helps and please don't hesitate to reach out to me if you have any further questions or suggestions.

Best,
Keegan
